[tool.ruff]
target-version = "py312"
line-length = 120
exclude = ["venv"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "BLE001",
    "C901",
    "COM812",
    "D",
    "FIX002",
    "ISC001",
    "PLR0911",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR5501",
    "PT009",
    "S101",
    "TD003",
    "UP040",
] # TODO leave only "COM812", "ANN102", "UP040" in ignores

[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true
plugins = ["pydantic.mypy"]
